# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Daren Tan
tagline:             'Web Developer | Mobile Developer | UX Designer | Data Scientist'
description:         '...'
url:                 http://www.darentan.com/blog
baseurl:             ''
paginate:            5
highlighter: rouge

# About/contact
author:
  name:              Daren Tan
  url:               http://www.darentan.tk
  email:             hello@darentan.tk

# Custom vars
version:             1.0.0
